# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 620cf8fec33fb321336e3b4c57f5f324d888272dc928bf2d2d1358b60f9ba10bd258fbb0d740a4d7722166f978d102a96eec55ba2d08979cbf0ba25eba942ec4

test:
  secret_key_base: 8a504eed9805b9474acf6180ccf09db1c72b21bb1e9466ddc2a3c927210441cfabf6f889515864fe7858da5584a5b0cd60a518e8fb979c73b80048db480978e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
