# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4297448a477b2bd59980e7ffdfe87f162b0bdcecdd44a1e77c139d330c48721797f0693ecccc9d6796c2da9c98eab2332630f9a725460693876740e1821cd95

test:
  secret_key_base: bf403dd1e4de0b3f34763adbc8215a421a4ab63fe1afedc924ea0fad0abc322c144f5fd3b19cf88378093a3339d06960b66775af4eb0bf755dece106aba3f40d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
